name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Changed from 'adopt' to 'temurin'

      - name: Build with Maven
        run: |
          mvn clean
          mvn vaadin:prepare-frontend
          mvn install

      - name: Run unit tests
        run: mvn test

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
